name = "arithmetic_geometric_mean_fortran"
version = "0.5.0"
license = "mit"
author = "DSCF-1224"
maintainer = "37315588+DSCF-1224@users.noreply.github.com"
copyright = "Copyright 2025, DSCF-1224"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[[test]]
name = "compiler"
source-dir = "test"
main = "check_compiler.f90"

[test.dependencies]
ieee_class_fortran = { git = "https://github.com/DSCF-1224/ieee_class_fortran", branch = "main" }
