name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:

  fypp:

    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fypp (src)
        run: |
          cd src
          fypp -F arithmetic_geometric_mean_fortran.fypp arithmetic_geometric_mean_fortran.f90
          cd ..

      - name: Run fypp (test)
        run: |
          cd test
          fypp -F check_nan.fypp check_nan.f90
          cd ..

      - name: Upload artifacts (src)
        uses: actions/upload-artifact@v4
        with:
          name: src-f90
          path: src/*.f90
          retention-days: 1

  test:

    needs: fypp

    timeout-minutes: 10

    runs-on: ubuntu-latest

    strategy:
      matrix:
        profile: [debug, release]
      fail-fast: false

    steps:

      - uses: actions/checkout@v5

      - name: Get .f90 files generated by fypp (src)
        uses: actions/download-artifact@v4
        with:
          name: src-f90
          path: src

      - name: Install fpm
        uses: fortran-lang/setup-fpm@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build library using fpm
        run: fpm build --profile ${{ matrix.profile }}

      - name: Test library using fpm (${{ matrix.profile }} mode)
        run: fpm test --profile ${{ matrix.profile }}

  commit:

    needs: test

    timeout-minutes: 10

    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: |
      github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')

    steps:

      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get .f90 files generated by fypp (src)
        uses: actions/download-artifact@v4
        with:
          name: src-f90
          path: src

      - name: Commit and push generated files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add src/*.f90

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generate .f90 files from fypp [skip ci]"
            git push
          fi
